#!/bin/sh
LIB=/usr/local/java/lib
java -server -cp /Users/hickst/lang/clojure/ica2gat/test:/Users/hickst/lang/clojure/ica2gat/test-resources:/Users/hickst/lang/clojure/ica2gat/src:/Users/hickst/lang/clojure/ica2gat/classes:/Users/hickst/lang/clojure/ica2gat/resources:/Users/hickst/lang/clojure/ica2gat/lib/clojure-1.3.0.jar:/Users/hickst/lang/clojure/ica2gat/lib/clojure-contrib-1.2.0.jar:/Users/hickst/lang/clojure/ica2gat/lib/math.combinatorics-0.0.2.jar:/Users/hickst/lang/clojure/ica2gat/lib/tools.cli-0.2.1.jar:${LIB}/jline.jar: jline.ConsoleRunner clojure.main $*
